### ISSUE TITLE
Search tracks

### ISSUE THREAD

**Issue by foshechka** [iambnz/SourSound#2]
Search tracks by genre, charts, popular.

**Comment by iambnz** [comment]
i have just pushed 2 new methods: searchUserByName, searchTracksByGenre

here you can test them
http://os.bnz-power.com/soursound/#/search/user
http://os.bnz-power.com/soursound/#/search/tracks/genres

more flexible, structured search soon.

**Comment by foshechka** [comment]
Cool

**Comment by iambnz** [comment]
closed, please check the updated readme - its deprecated from now on. 

thanks for your support!
